In [10]:
import requests
import pandas as pd

def make_invest_dataframe(firm_code):
    invest_url = 'http://comp.fnguide.com/SVO2/ASP/SVD_Invest.asp?pGB=1&cID=&MenuYn=Y&ReportGB=&NewMenuID=105&stkGb=701&gicode=' + firm_code
    invest_page = requests.get(invest_url)
    invest_tables = pd.read_html(invest_page.text)

    temp_df = invest_tables[1]
    temp_df = temp_df.set_index(temp_df.columns[0])
    temp_df = temp_df.loc[[
        'PER계산에 참여한 계정 펼치기',
        'PCR계산에 참여한 계정 펼치기',
        'PSR계산에 참여한 계정 펼치기',
        'PBR계산에 참여한 계정 펼치기',
        '총현금흐름'
    ]]
    temp_df.index = ['PER','PCR','PSR','PBR','총현금흐름']
    
    return temp_df

In [11]:
def change_df(firm_code, dataframe):
    for num, col in enumerate(dataframe.columns):
        temp_df = pd.DataFrame({firm_code:dataframe[col]})
        temp_df = temp_df.T
        temp_df.columns = [[col]*len(dataframe), temp_df.columns]

        if num == 0:
            total_df = temp_df
        else:
            total_df = pd.merge(total_df, temp_df, how='outer', left_index=True, right_index=True)
            
    return total_df

In [12]:
firm_code_list = ['A005930','A035420']

for num, code in enumerate(firm_code_list):
    invest_df = make_invest_dataframe(code)
    invest_df_changed = change_df(code, invest_df)
    
    if num == 0:
        total_invest = invest_df_changed
    else:
        total_invest = pd.concat([total_invest, invest_df_changed])

In [9]:
total_invest

        2015/12                            2016/12                             \
            PER    PCR   PSR   PBR   총현금흐름     PER    PCR   PSR   PBR   총현금흐름
A005930   11.47   5.41  1.07  1.15  403232   13.18   6.85  1.46  1.48  423491
A035420   41.87  32.19  6.68  6.83    7553   34.14  28.04  6.36  5.17    9136

         ... 2018/12                            2019/12                     \
         ...     PER    PCR   PSR   PBR   총현금흐름     PER    PCR   PSR   PBR
A005930  ...    6.42   4.01  1.16  1.10  691786   17.63   7.42  1.65  1.49
A035420  ...   30.99  22.10  3.60  3.08    7892   52.72  28.43  4.66  4.27


          총현금흐름
A005930  494337
A035420    8261

[2 rows x 25 columns]